/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Platform } from './Platform';
import {
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
    PlatformToJSONTyped,
} from './Platform';

/**
 * Schema for contact data in responses.
 * @export
 * @interface ContactOut
 */
export interface ContactOut {
    /**
     * 
     * @type {Platform}
     * @memberof ContactOut
     */
    platform: Platform;
    /**
     * 
     * @type {string}
     * @memberof ContactOut
     */
    platformUserId: string;
    /**
     * 
     * @type {string}
     * @memberof ContactOut
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactOut
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactOut
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContactOut
     */
    optOut?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ContactOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ContactOut
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the ContactOut interface.
 */
export function instanceOfContactOut(value: object): value is ContactOut {
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('platformUserId' in value) || value['platformUserId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ContactOutFromJSON(json: any): ContactOut {
    return ContactOutFromJSONTyped(json, false);
}

export function ContactOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactOut {
    if (json == null) {
        return json;
    }
    return {
        
        'platform': PlatformFromJSON(json['platform']),
        'platformUserId': json['platformUserId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'],
        'optOut': json['optOut'] == null ? undefined : json['optOut'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ContactOutToJSON(json: any): ContactOut {
    return ContactOutToJSONTyped(json, false);
}

export function ContactOutToJSONTyped(value?: ContactOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform': PlatformToJSON(value['platform']),
        'platformUserId': value['platformUserId'],
        'phone': value['phone'],
        'name': value['name'],
        'id': value['id'],
        'optOut': value['optOut'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

