/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for updating contact opt-out status.
 * @export
 * @interface ContactOptOutUpdate
 */
export interface ContactOptOutUpdate {
    /**
     * 
     * @type {boolean}
     * @memberof ContactOptOutUpdate
     */
    optOut: boolean;
}

/**
 * Check if a given object implements the ContactOptOutUpdate interface.
 */
export function instanceOfContactOptOutUpdate(value: object): value is ContactOptOutUpdate {
    if (!('optOut' in value) || value['optOut'] === undefined) return false;
    return true;
}

export function ContactOptOutUpdateFromJSON(json: any): ContactOptOutUpdate {
    return ContactOptOutUpdateFromJSONTyped(json, false);
}

export function ContactOptOutUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactOptOutUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'optOut': json['optOut'],
    };
}

export function ContactOptOutUpdateToJSON(json: any): ContactOptOutUpdate {
    return ContactOptOutUpdateToJSONTyped(json, false);
}

export function ContactOptOutUpdateToJSONTyped(value?: ContactOptOutUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'optOut': value['optOut'],
    };
}

