/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactOut } from './ContactOut';
import {
    ContactOutFromJSON,
    ContactOutFromJSONTyped,
    ContactOutToJSON,
    ContactOutToJSONTyped,
} from './ContactOut';
import type { ConversationStatus } from './ConversationStatus';
import {
    ConversationStatusFromJSON,
    ConversationStatusFromJSONTyped,
    ConversationStatusToJSON,
    ConversationStatusToJSONTyped,
} from './ConversationStatus';

/**
 * Schema for conversation with nested contact data.
 * @export
 * @interface ConversationWithContact
 */
export interface ConversationWithContact {
    /**
     * 
     * @type {string}
     * @memberof ConversationWithContact
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationWithContact
     */
    contactId: string;
    /**
     * 
     * @type {ConversationStatus}
     * @memberof ConversationWithContact
     */
    status: ConversationStatus;
    /**
     * 
     * @type {Date}
     * @memberof ConversationWithContact
     */
    lastMessageAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ConversationWithContact
     */
    createdAt: Date;
    /**
     * 
     * @type {ContactOut}
     * @memberof ConversationWithContact
     */
    contact: ContactOut;
}



/**
 * Check if a given object implements the ConversationWithContact interface.
 */
export function instanceOfConversationWithContact(value: object): value is ConversationWithContact {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contactId' in value) || value['contactId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('lastMessageAt' in value) || value['lastMessageAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    return true;
}

export function ConversationWithContactFromJSON(json: any): ConversationWithContact {
    return ConversationWithContactFromJSONTyped(json, false);
}

export function ConversationWithContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationWithContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contactId': json['contactId'],
        'status': ConversationStatusFromJSON(json['status']),
        'lastMessageAt': (new Date(json['lastMessageAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'contact': ContactOutFromJSON(json['contact']),
    };
}

export function ConversationWithContactToJSON(json: any): ConversationWithContact {
    return ConversationWithContactToJSONTyped(json, false);
}

export function ConversationWithContactToJSONTyped(value?: ConversationWithContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'contactId': value['contactId'],
        'status': ConversationStatusToJSON(value['status']),
        'lastMessageAt': value['lastMessageAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'contact': ContactOutToJSON(value['contact']),
    };
}

