/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationWithContact } from './ConversationWithContact';
import {
    ConversationWithContactFromJSON,
    ConversationWithContactFromJSONTyped,
    ConversationWithContactToJSON,
    ConversationWithContactToJSONTyped,
} from './ConversationWithContact';

/**
 * Schema for paginated conversation list.
 * @export
 * @interface ConversationListResponse
 */
export interface ConversationListResponse {
    /**
     * 
     * @type {Array<ConversationWithContact>}
     * @memberof ConversationListResponse
     */
    items: Array<ConversationWithContact>;
    /**
     * 
     * @type {number}
     * @memberof ConversationListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ConversationListResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ConversationListResponse
     */
    offset: number;
}

/**
 * Check if a given object implements the ConversationListResponse interface.
 */
export function instanceOfConversationListResponse(value: object): value is ConversationListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ConversationListResponseFromJSON(json: any): ConversationListResponse {
    return ConversationListResponseFromJSONTyped(json, false);
}

export function ConversationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ConversationWithContactFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ConversationListResponseToJSON(json: any): ConversationListResponse {
    return ConversationListResponseToJSONTyped(json, false);
}

export function ConversationListResponseToJSONTyped(value?: ConversationListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ConversationWithContactToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

