/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Conversation status options.
 * @export
 */
export const ConversationStatus = {
    Open: 'OPEN',
    Closed: 'CLOSED'
} as const;
export type ConversationStatus = typeof ConversationStatus[keyof typeof ConversationStatus];


export function instanceOfConversationStatus(value: any): boolean {
    for (const key in ConversationStatus) {
        if (Object.prototype.hasOwnProperty.call(ConversationStatus, key)) {
            if (ConversationStatus[key as keyof typeof ConversationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConversationStatusFromJSON(json: any): ConversationStatus {
    return ConversationStatusFromJSONTyped(json, false);
}

export function ConversationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationStatus {
    return json as ConversationStatus;
}

export function ConversationStatusToJSON(value?: ConversationStatus | null): any {
    return value as any;
}

export function ConversationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ConversationStatus {
    return value as ConversationStatus;
}

