/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSendRequest
 */
export interface EmailSendRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailSendRequest
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSendRequest
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSendRequest
     */
    text?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailSendRequest
     */
    html?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailSendRequest
     */
    template?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EmailSendRequest
     */
    params?: { [key: string]: any; };
}

/**
 * Check if a given object implements the EmailSendRequest interface.
 */
export function instanceOfEmailSendRequest(value: object): value is EmailSendRequest {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function EmailSendRequestFromJSON(json: any): EmailSendRequest {
    return EmailSendRequestFromJSONTyped(json, false);
}

export function EmailSendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'subject': json['subject'],
        'text': json['text'] == null ? undefined : json['text'],
        'html': json['html'] == null ? undefined : json['html'],
        'template': json['template'] == null ? undefined : json['template'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function EmailSendRequestToJSON(json: any): EmailSendRequest {
    return EmailSendRequestToJSONTyped(json, false);
}

export function EmailSendRequestToJSONTyped(value?: EmailSendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'subject': value['subject'],
        'text': value['text'],
        'html': value['html'],
        'template': value['template'],
        'params': value['params'],
    };
}

