/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSendResponse
 */
export interface EmailSendResponse {
    /**
     * 
     * @type {boolean}
     * @memberof EmailSendResponse
     */
    accepted: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmailSendResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the EmailSendResponse interface.
 */
export function instanceOfEmailSendResponse(value: object): value is EmailSendResponse {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    return true;
}

export function EmailSendResponseFromJSON(json: any): EmailSendResponse {
    return EmailSendResponseFromJSONTyped(json, false);
}

export function EmailSendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSendResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function EmailSendResponseToJSON(json: any): EmailSendResponse {
    return EmailSendResponseToJSONTyped(json, false);
}

export function EmailSendResponseToJSONTyped(value?: EmailSendResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'message': value['message'],
    };
}

