/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Platform } from './Platform';
import {
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
    PlatformToJSONTyped,
} from './Platform';

/**
 * 
 * @export
 * @interface MessageOut
 */
export interface MessageOut {
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    conversationId: string;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    fromUserId?: string | null;
    /**
     * 
     * @type {Platform}
     * @memberof MessageOut
     */
    platform: Platform;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    text?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    mediaUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    remoteMessageId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MessageOut
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the MessageOut interface.
 */
export function instanceOfMessageOut(value: object): value is MessageOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function MessageOutFromJSON(json: any): MessageOut {
    return MessageOutFromJSONTyped(json, false);
}

export function MessageOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'conversationId': json['conversationId'],
        'fromUserId': json['fromUserId'] == null ? undefined : json['fromUserId'],
        'platform': PlatformFromJSON(json['platform']),
        'text': json['text'] == null ? undefined : json['text'],
        'mediaUrl': json['mediaUrl'] == null ? undefined : json['mediaUrl'],
        'remoteMessageId': json['remoteMessageId'] == null ? undefined : json['remoteMessageId'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function MessageOutToJSON(json: any): MessageOut {
    return MessageOutToJSONTyped(json, false);
}

export function MessageOutToJSONTyped(value?: MessageOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'conversationId': value['conversationId'],
        'fromUserId': value['fromUserId'],
        'platform': PlatformToJSON(value['platform']),
        'text': value['text'],
        'mediaUrl': value['mediaUrl'],
        'remoteMessageId': value['remoteMessageId'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

