/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for updating a product.
 * @export
 * @interface ProductUpdate
 */
export interface ProductUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdate
     */
    priceCents?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    stripePriceId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductUpdate
     */
    isActive?: boolean | null;
}

/**
 * Check if a given object implements the ProductUpdate interface.
 */
export function instanceOfProductUpdate(value: object): value is ProductUpdate {
    return true;
}

export function ProductUpdateFromJSON(json: any): ProductUpdate {
    return ProductUpdateFromJSONTyped(json, false);
}

export function ProductUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'priceCents': json['priceCents'] == null ? undefined : json['priceCents'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'stripePriceId': json['stripePriceId'] == null ? undefined : json['stripePriceId'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function ProductUpdateToJSON(json: any): ProductUpdate {
    return ProductUpdateToJSONTyped(json, false);
}

export function ProductUpdateToJSONTyped(value?: ProductUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'priceCents': value['priceCents'],
        'currency': value['currency'],
        'imageUrl': value['imageUrl'],
        'description': value['description'],
        'stripePriceId': value['stripePriceId'],
        'isActive': value['isActive'],
    };
}

