/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for product data in responses.
 * @export
 * @interface ProductOut
 */
export interface ProductOut {
    /**
     * 
     * @type {string}
     * @memberof ProductOut
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ProductOut
     */
    priceCents: number;
    /**
     * 
     * @type {string}
     * @memberof ProductOut
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOut
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductOut
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductOut
     */
    stripePriceId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOut
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductOut
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProductOut
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductOut
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ProductOut interface.
 */
export function instanceOfProductOut(value: object): value is ProductOut {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('priceCents' in value) || value['priceCents'] === undefined) return false;
    if (!('stripePriceId' in value) || value['stripePriceId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProductOutFromJSON(json: any): ProductOut {
    return ProductOutFromJSONTyped(json, false);
}

export function ProductOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOut {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'priceCents': json['priceCents'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'stripePriceId': json['stripePriceId'],
        'id': json['id'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ProductOutToJSON(json: any): ProductOut {
    return ProductOutToJSONTyped(json, false);
}

export function ProductOutToJSONTyped(value?: ProductOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'priceCents': value['priceCents'],
        'currency': value['currency'],
        'imageUrl': value['imageUrl'],
        'description': value['description'],
        'stripePriceId': value['stripePriceId'],
        'id': value['id'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

