/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductOut } from './ProductOut';
import {
    ProductOutFromJSON,
    ProductOutFromJSONTyped,
    ProductOutToJSON,
    ProductOutToJSONTyped,
} from './ProductOut';

/**
 * Schema for product list response.
 * @export
 * @interface ProductListResponse
 */
export interface ProductListResponse {
    /**
     * 
     * @type {Array<ProductOut>}
     * @memberof ProductListResponse
     */
    items: Array<ProductOut>;
    /**
     * 
     * @type {number}
     * @memberof ProductListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ProductListResponse interface.
 */
export function instanceOfProductListResponse(value: object): value is ProductListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ProductListResponseFromJSON(json: any): ProductListResponse {
    return ProductListResponseFromJSONTyped(json, false);
}

export function ProductListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductOutFromJSON)),
        'total': json['total'],
    };
}

export function ProductListResponseToJSON(json: any): ProductListResponse {
    return ProductListResponseToJSONTyped(json, false);
}

export function ProductListResponseToJSONTyped(value?: ProductListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductOutToJSON)),
        'total': value['total'],
    };
}

