/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating a new product.
 * @export
 * @interface ProductCreate
 */
export interface ProductCreate {
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreate
     */
    priceCents: number;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCreate
     */
    stripePriceId: string;
}

/**
 * Check if a given object implements the ProductCreate interface.
 */
export function instanceOfProductCreate(value: object): value is ProductCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('priceCents' in value) || value['priceCents'] === undefined) return false;
    if (!('stripePriceId' in value) || value['stripePriceId'] === undefined) return false;
    return true;
}

export function ProductCreateFromJSON(json: any): ProductCreate {
    return ProductCreateFromJSONTyped(json, false);
}

export function ProductCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'priceCents': json['priceCents'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'stripePriceId': json['stripePriceId'],
    };
}

export function ProductCreateToJSON(json: any): ProductCreate {
    return ProductCreateToJSONTyped(json, false);
}

export function ProductCreateToJSONTyped(value?: ProductCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'priceCents': value['priceCents'],
        'currency': value['currency'],
        'imageUrl': value['imageUrl'],
        'description': value['description'],
        'stripePriceId': value['stripePriceId'],
    };
}

