/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageOut } from './MessageOut';
import {
    MessageOutFromJSON,
    MessageOutFromJSONTyped,
    MessageOutToJSON,
    MessageOutToJSONTyped,
} from './MessageOut';

/**
 * Schema for send message response.
 * @export
 * @interface SendMessageResponse
 */
export interface SendMessageResponse {
    /**
     * 
     * @type {MessageOut}
     * @memberof SendMessageResponse
     */
    message: MessageOut;
    /**
     * 
     * @type {string}
     * @memberof SendMessageResponse
     */
    remoteMessageId?: string | null;
}

/**
 * Check if a given object implements the SendMessageResponse interface.
 */
export function instanceOfSendMessageResponse(value: object): value is SendMessageResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SendMessageResponseFromJSON(json: any): SendMessageResponse {
    return SendMessageResponseFromJSONTyped(json, false);
}

export function SendMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': MessageOutFromJSON(json['message']),
        'remoteMessageId': json['remoteMessageId'] == null ? undefined : json['remoteMessageId'],
    };
}

export function SendMessageResponseToJSON(json: any): SendMessageResponse {
    return SendMessageResponseToJSONTyped(json, false);
}

export function SendMessageResponseToJSONTyped(value?: SendMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': MessageOutToJSON(value['message']),
        'remoteMessageId': value['remoteMessageId'],
    };
}

