/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for sending a message.
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    conversationId: string;
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    text?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    agentUserId?: string | null;
}

/**
 * Check if a given object implements the SendMessageRequest interface.
 */
export function instanceOfSendMessageRequest(value: object): value is SendMessageRequest {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    return true;
}

export function SendMessageRequestFromJSON(json: any): SendMessageRequest {
    return SendMessageRequestFromJSONTyped(json, false);
}

export function SendMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'text': json['text'] == null ? undefined : json['text'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'agentUserId': json['agentUserId'] == null ? undefined : json['agentUserId'],
    };
}

export function SendMessageRequestToJSON(json: any): SendMessageRequest {
    return SendMessageRequestToJSONTyped(json, false);
}

export function SendMessageRequestToJSONTyped(value?: SendMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationId': value['conversationId'],
        'text': value['text'],
        'imageUrl': value['imageUrl'],
        'agentUserId': value['agentUserId'],
    };
}

