/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuggestionOut
 */
export interface SuggestionOut {
    /**
     * 
     * @type {string}
     * @memberof SuggestionOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SuggestionOut
     */
    conversationId: string;
    /**
     * 
     * @type {string}
     * @memberof SuggestionOut
     */
    text: string;
    /**
     * 
     * @type {Date}
     * @memberof SuggestionOut
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the SuggestionOut interface.
 */
export function instanceOfSuggestionOut(value: object): value is SuggestionOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SuggestionOutFromJSON(json: any): SuggestionOut {
    return SuggestionOutFromJSONTyped(json, false);
}

export function SuggestionOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestionOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'conversationId': json['conversationId'],
        'text': json['text'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function SuggestionOutToJSON(json: any): SuggestionOut {
    return SuggestionOutToJSONTyped(json, false);
}

export function SuggestionOutToJSONTyped(value?: SuggestionOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'conversationId': value['conversationId'],
        'text': value['text'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

