/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserOut } from './UserOut';
import {
    UserOutFromJSON,
    UserOutFromJSONTyped,
    UserOutToJSON,
    UserOutToJSONTyped,
} from './UserOut';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * Schema for user data with authentication tokens.
 * @export
 * @interface UserWithTokens
 */
export interface UserWithTokens {
    /**
     * 
     * @type {UserOut}
     * @memberof UserWithTokens
     */
    user: UserOut;
    /**
     * 
     * @type {Token}
     * @memberof UserWithTokens
     */
    tokens?: Token | null;
}

/**
 * Check if a given object implements the UserWithTokens interface.
 */
export function instanceOfUserWithTokens(value: object): value is UserWithTokens {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UserWithTokensFromJSON(json: any): UserWithTokens {
    return UserWithTokensFromJSONTyped(json, false);
}

export function UserWithTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserOutFromJSON(json['user']),
        'tokens': json['tokens'] == null ? undefined : TokenFromJSON(json['tokens']),
    };
}

export function UserWithTokensToJSON(json: any): UserWithTokens {
    return UserWithTokensToJSONTyped(json, false);
}

export function UserWithTokensToJSONTyped(value?: UserWithTokens | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserOutToJSON(value['user']),
        'tokens': TokenToJSON(value['tokens']),
    };
}

