services:
  br-postgres-general:
    build:
      context: .
      dockerfile: ./postgres/postgres-general.Dockerfile
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - br-postgres-general:/var/lib/postgresql/data
    env_file:
      - ./br-general-python/.env
    networks:
      - app-network

  br-general-python:
    build:
      context: .
      dockerfile: br-general-python/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - br-postgres-general
    networks:
      - app-network

  br-web:
    build:
      context: .
      dockerfile: ./pt-web/Dockerfile
    ports:
      - "127.0.0.1:5174:80"
    networks:
      - app-network

  br-gateway:
    image: caddy:2.8-alpine
    container_name: caddy-local
    depends_on:
      - br-general-python
      - br-web
    ports:
      - "80:80"
    volumes:
      - ./gateway/Caddyfile.local:/etc/caddy/Caddyfile:ro
    networks:
      - app-network

volumes:
  br-postgres-general:

networks:
  app-network:
    driver: bridge