import {ContactOut, instanceOfContactOut} from "src/apiAutogenerated/typescript-fetch/models";

export enum Platform {
    WHATSAPP = "WHATSAPP",
    MESSENGER = "MESSENGER",
    INSTAGRAM = "INSTAGRAM"
}

export type ContactModel = {
   id: string;
   platform: Platform;
   platformUserId: string;
   phone?: string | null;
   name?: string | null;
   optOut?: boolean;
}

/**
 * Maps a {@link ContactOut} DTO to a {@link ContactModel}.
 *
 * Validates the input DTO type before transforming it into the internal
 * contact model representation.
 *
 * @param dto - The contact DTO received from the API.
 * @returns The mapped {@link ContactModel}.
 *
 * @throws {Error} If the provided DTO is not an instance of {@link ContactOut}.
 */
export function contactModelFromContactOut (dto: ContactOut): ContactModel {
  if (!instanceOfContactOut(dto)) {
    throw new Error("dto mapping error: dto not instance of instanceOfContactOut");
  }
  const model: ContactModel = {
    id: dto.id,
    platform: Platform[dto.platform],
    platformUserId: dto.platformUserId,
    phone: dto.phone,
    name: dto.name,
    optOut: dto.optOut,
  };

  return model;
};
