import {
  ConversationListResponse,
  ConversationWithContact,
  instanceOfConversationListResponse,
  instanceOfConversationWithContact,
} from "src/apiAutogenerated/typescript-fetch/models";
import {ContactModel, contactModelFromContactOut} from "src/models/Contact";

// Conversation status options.
// Linked DTO - pt-web/src/apiAutogenerated/typescript-fetch/models/ConversationStatus.ts
export enum ConversationStatus {
    OPEN = "OPEN",
    CLOSED = "CLOSED",
  }

// Schema for conversation with nested contact data.
// Linked DTO - pt-web/src/apiAutogenerated/typescript-fetch/models/ConversationWithContact.ts
export type ConversationModel = {
    id: string;
    contactId: string;
    status: ConversationStatus;
    lastMessageAt: Date;
    createdAt: Date;
    contact: ContactModel;
}

// Schema for paginated conversation list.
// Linked DTO - pt-web/src/apiAutogenerated/typescript-fetch/models/ConversationListResponse.ts
export type ConversationListModel = {
    items: ConversationModel[];
    total: number;
    limit: number;
    offset: number;
}

/**
 * Maps a {@link ConversationWithContact} DTO to a {@link ConversationModel}.
 *
 * Validates the input DTO type before transforming it into the internal
 * conversation model used by the application.
 *
 * @param dto - The conversation DTO containing contact information.
 * @returns The mapped {@link ConversationModel}.
 *
 * @throws {Error} If the provided DTO is not an instance of {@link ConversationWithContact}.
 */
export function conversationModelFromConversationWithContact(dto: ConversationWithContact): ConversationModel {
  if (!instanceOfConversationWithContact(dto)) {
    throw new Error("dto mapping error: dto not instance of ConversationWithContact");
  }
  const model: ConversationModel = {
    id: dto.id,
    contactId: dto.contactId,
    status: ConversationStatus[dto.status],
    lastMessageAt: dto.lastMessageAt,
    createdAt: dto.createdAt,
    contact: contactModelFromContactOut(dto.contact),
  };

  return model;
}

/**
 * Maps a {@link ConversationListResponse} DTO to a {@link ConversationListModel}.
 *
 * Validates the input DTO type before transforming it into the internal
 * paginated conversation list model.
 *
 * @param dto - The conversation list response DTO.
 * @returns The mapped {@link ConversationListModel}.
 *
 * @throws {Error} If the provided DTO is not an instance of {@link ConversationListResponse}.
 */
export function conversationListModelFromConversationListResponse(dto: ConversationListResponse): ConversationListModel {
  if (!instanceOfConversationListResponse(dto)) {
    throw new Error("dto mapping error: dto not instance of ConversationListResponse");
  }
  const model: ConversationListModel = {
    items: dto.items.map(conversationWithContact => conversationModelFromConversationWithContact(conversationWithContact)),
    limit: dto.limit,
    offset: dto.offset,
    total: dto.total,
  };

  return model;
}
