import {instanceOfMessageOut, MessageOut} from "src/apiAutogenerated/typescript-fetch/models";
import {Platform} from "src/models/Contact";

// Linked DTO - pt-web/src/apiAutogenerated/typescript-fetch/models/MessageOut.ts
export type MessageModel = {
    id: string;
    conversationId: string;
    fromUserId?: string | null;
    platform: Platform;
    text?: string | null;
    mediaUrl?: string | null;
    remoteMessageId?: string | null;
    createdAt: Date;
}

/**
 * Maps a {@link MessageOut} DTO to a {@link MessageModel} model.
 *
 * Validates the input DTO type before transforming it into the internal
 * message model used by the application.
 *
 * @param dto - The message DTO received from the API.
 * @returns The mapped {@link MessageModel}.
 *
 * @throws {Error} If the provided DTO is not an instance of {@link MessageOut}.
 */
export function messageModelFromMessageOut(dto: MessageOut): MessageModel {
  if (!instanceOfMessageOut(dto)) {
    throw new Error("dto mapping error: dto not instance of MessageOut");
  }
  const model: MessageModel = {
    id: dto.id,
    conversationId: dto.conversationId,
    fromUserId: dto.fromUserId,
    platform: Platform[dto.platform],
    text: dto.text,
    mediaUrl: dto.mediaUrl,
    remoteMessageId: dto.remoteMessageId,
    createdAt: dto.createdAt,
  };

  return model;
}

/**
 * Maps a list of {@link MessageOut} DTOs to a list of {@link MessageModel}.
 *
 * @param dto - The array of message DTOs received from the API.
 * @returns An array of mapped {@link MessageModel}.
 */
export function messageModelListFromMessageOutList(dto: MessageOut[]): MessageModel[] {
  return dto.map((messageOut: MessageOut) => messageModelFromMessageOut(messageOut));
}
