import {instanceOfSuggestionOut, SuggestionOut} from "src/apiAutogenerated/typescript-fetch/models";

// Linked DTO - pt-web/src/apiAutogenerated/typescript-fetch/models/SuggestionOut.ts
export type SuggestionModel = {
    id: string;
    conversationId: string;
    text: string;
    createdAt: Date;
}

/**
 * Maps a {@link SuggestionOut} DTO to a {@link SuggestionModel}.
 *
 * Validates the input DTO type before transforming it into the internal
 * suggestion model used by the application.
 *
 * @param dto - The suggestion DTO received from the API.
 * @returns The mapped {@link SuggestionModel}.
 *
 * @throws {Error} If the provided DTO is not an instance of {@link SuggestionOut}.
 */
export function suggestionModelFromSuggestionOut(dto: SuggestionOut): SuggestionModel {
  if (!instanceOfSuggestionOut(dto)) {
    throw new Error("dto mapping error: dto not instance of SuggestionOut");
  }
  const model: SuggestionModel = {
    id: dto.id,
    conversationId: dto.conversationId,
    text: dto.text,
    createdAt: dto.createdAt,
  };

  return model;
}

/**
 * Maps a list of {@link SuggestionOut} DTOs to a list of {@link SuggestionModel}.
 *
 * @param dto - The array of suggestion DTOs received from the API.
 * @returns An array of mapped {@link SuggestionModel}.
 */
export function suggestionModelListFromSuggestionOutList(dto: SuggestionOut[]): SuggestionModel[] {
  return dto.map((suggestionOut: SuggestionOut) => suggestionModelFromSuggestionOut(suggestionOut));
}
