import {instanceOfUserOut, UserOut} from "src/apiAutogenerated/typescript-fetch/models";

export enum UserRole {
    ADMIN = "ADMIN",
    AGENT = "AGENT",
  }

// Linked DTO - pt-web/src/apiAutogenerated/typescript-fetch/models/UserOut.ts
export type UserProfileModel = {
  id: string;
  email: string;
  name: string;
  role: UserRole;
};

/**
 * Maps a {@link UserOut} DTO to a {@link UserProfileModel}.
 *
 * Validates the input DTO type before transforming it into the internal
 * user profile model.
 *
 * @param dto - The user DTO received from the API.
 * @returns The mapped {@link UserProfileModel}.
 *
 * @throws {Error} If the provided DTO is not an instance of {@link UserOut}.
 */
export function userProfileModelFromUserOut(dto: UserOut): UserProfileModel {
  if (!instanceOfUserOut(dto)) {
    throw new Error("dto mapping error: dto not instance of UserOut");
  }
  const model: UserProfileModel = {
    id: dto.id,
    email: dto.email,
    name: dto.name,
    role: UserRole[dto.role],
  };

  return model;
}
