/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

/**
 * 
 */
export class AiApi {

    /**
     * Generate an AI-drafted response for a conversation.
     * Generate Draft
     */
    async generateDraft(conversationId: string, style?: string | null, initOverrides?: RequestInit): Promise<any> { 
        if (conversationId == null) {
            throw new Error(
                'Required parameter "conversationId" was null or undefined when calling generateDraft().'
            );
        }

        const queryParameters: Record<string, string> = {};

        if (conversationId != null) {
            queryParameters['conversation_id'] = String(conversationId);
        }
        if (style != null) {
            queryParameters['style'] = String(style);
        }
        
        let urlPath = `/br-general/ai/draft`;

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Get available canned prompt options.
     * Get Canned Prompts
     */
    async getCannedPrompts(initOverrides?: RequestInit): Promise<any> { 
        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/ai/prompts`;

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

}

export const aiApi = new AiApi();