/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  HTTPValidationError,
  LogoutResponse,
  RefreshTokenRequest,
  UserCreate,
  UserWithTokens,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LogoutResponseFromJSON,
    LogoutResponseToJSON,
    RefreshTokenRequestFromJSON,
    RefreshTokenRequestToJSON,
    UserCreateFromJSON,
    UserCreateToJSON,
    UserWithTokensFromJSON,
    UserWithTokensToJSON,
} from '../models/index';

/**
 * 
 */
export class AuthApi {

    /**
     * Login Full
     */
    async loginFull(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, initOverrides?: RequestInit): Promise<UserWithTokens> { 
        if (username == null) {
            throw new Error(
                'Required parameter "username" was null or undefined when calling loginFull().'
            );
        }

        if (password == null) {
            throw new Error(
                'Required parameter "password" was null or undefined when calling loginFull().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/auth/login/full`;

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Login Oauth
     */
    async loginOauth(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, initOverrides?: RequestInit): Promise<any> { 
        if (username == null) {
            throw new Error(
                'Required parameter "username" was null or undefined when calling loginOauth().'
            );
        }

        if (password == null) {
            throw new Error(
                'Required parameter "password" was null or undefined when calling loginOauth().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/auth/login`;

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Stateless logout. Client discards tokens.
     * Logout
     */
    async logout(initOverrides?: RequestInit): Promise<LogoutResponse> { 
        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/auth/logout`;

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Refresh Tokens
     */
    async refreshTokens(refreshTokenRequest: RefreshTokenRequest, initOverrides?: RequestInit): Promise<UserWithTokens> { 
        if (refreshTokenRequest == null) {
            throw new Error(
                'Required parameter "refreshTokenRequest" was null or undefined when calling refreshTokens().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/auth/refresh`;

        return await apiClient.request(
          "POST",
          urlPath,
          RefreshTokenRequestToJSON(refreshTokenRequest),
          initOverrides);

    }

    /**
     * Register a new user.
     * Register
     */
    async register(userCreate: UserCreate, initOverrides?: RequestInit): Promise<UserWithTokens> { 
        if (userCreate == null) {
            throw new Error(
                'Required parameter "userCreate" was null or undefined when calling register().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/auth/register`;

        return await apiClient.request(
          "POST",
          urlPath,
          UserCreateToJSON(userCreate),
          initOverrides);

    }

}

export const authApi = new AuthApi();