/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

/**
 * 
 */
export class CheckApi {

    /**
     * Broadcast Event
     */
    async broadcastEvent(requestBody: { [key: string]: any; }, initOverrides?: RequestInit): Promise<any> { 
        if (requestBody == null) {
            throw new Error(
                'Required parameter "requestBody" was null or undefined when calling broadcastEvent().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/check/broadcast`;

        return await apiClient.request(
          "POST",
          urlPath,
          requestBody,
          initOverrides);

    }

    /**
     * Inbound Message
     */
    async inboundMessage(requestBody: { [key: string]: any; }, initOverrides?: RequestInit): Promise<any> { 
        if (requestBody == null) {
            throw new Error(
                'Required parameter "requestBody" was null or undefined when calling inboundMessage().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/check/inbound-message`;

        return await apiClient.request(
          "POST",
          urlPath,
          requestBody,
          initOverrides);

    }

    /**
     * Ping
     */
    async ping(requestBody: { [key: string]: any; }, initOverrides?: RequestInit): Promise<any> { 
        if (requestBody == null) {
            throw new Error(
                'Required parameter "requestBody" was null or undefined when calling ping().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/check/ping`;

        return await apiClient.request(
          "POST",
          urlPath,
          requestBody,
          initOverrides);

    }

}

export const checkApi = new CheckApi();