/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  ContactOptOutUpdate,
  ConversationListResponse,
  ConversationStatus,
  ConversationWithContact,
  HTTPValidationError,
  MessageOut,
  SendMessageRequest,
  SendMessageResponse,
  SuggestionOut,
} from '../models/index';
import {
    ContactOptOutUpdateFromJSON,
    ContactOptOutUpdateToJSON,
    ConversationListResponseFromJSON,
    ConversationListResponseToJSON,
    ConversationStatusFromJSON,
    ConversationStatusToJSON,
    ConversationWithContactFromJSON,
    ConversationWithContactToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageOutFromJSON,
    MessageOutToJSON,
    SendMessageRequestFromJSON,
    SendMessageRequestToJSON,
    SendMessageResponseFromJSON,
    SendMessageResponseToJSON,
    SuggestionOutFromJSON,
    SuggestionOutToJSON,
} from '../models/index';

/**
 * 
 */
export class ConversationsApi {

    /**
     * Close a conversation.
     * Close Conversation
     */
    async closeConversation(conversationId: string, initOverrides?: RequestInit): Promise<void> { 
        if (conversationId == null) {
            throw new Error(
                'Required parameter "conversationId" was null or undefined when calling closeConversation().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/conversations/{conversation_id}/close`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Create Suggestions
     */
    async createSuggestions(conversationId: string, initOverrides?: RequestInit): Promise<Array<SuggestionOut>> { 
        if (conversationId == null) {
            throw new Error(
                'Required parameter "conversationId" was null or undefined when calling createSuggestions().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/conversations/{conversation_id}/suggestions`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Get a single conversation.
     * Get Conversation
     */
    async getConversation(conversationId: string, initOverrides?: RequestInit): Promise<ConversationWithContact> { 
        if (conversationId == null) {
            throw new Error(
                'Required parameter "conversationId" was null or undefined when calling getConversation().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/conversations/{conversation_id}`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

    /**
     * Get messages for a conversation.
     * Get Messages
     */
    async getMessages(conversationId: string, limit?: number, cursor?: string | null, initOverrides?: RequestInit): Promise<Array<MessageOut>> { 
        if (conversationId == null) {
            throw new Error(
                'Required parameter "conversationId" was null or undefined when calling getMessages().'
            );
        }

        const queryParameters: Record<string, string> = {};

        if (limit != null) {
            queryParameters['limit'] = String(limit);
        }
        if (cursor != null) {
            queryParameters['cursor'] = String(cursor);
        }
        
        let urlPath = `/conversations/{conversation_id}/messages`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

    /**
     * Get suggestions for a conversation. AGENT / ADMIN only.
     * Get Suggestions
     */
    async getSuggestions(conversationId: string, initOverrides?: RequestInit): Promise<Array<SuggestionOut>> { 
        if (conversationId == null) {
            throw new Error(
                'Required parameter "conversationId" was null or undefined when calling getSuggestions().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/conversations/{conversation_id}/suggestions`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

    /**
     * List conversations visible to the current user.
     * List Conversations
     */
    async listConversations(status?: ConversationStatus | null, limit?: number, offset?: number, initOverrides?: RequestInit): Promise<ConversationListResponse> { 
        const queryParameters: Record<string, string> = {};

        if (status != null) {
            queryParameters['status'] = String(status);
        }
        if (limit != null) {
            queryParameters['limit'] = String(limit);
        }
        if (offset != null) {
            queryParameters['offset'] = String(offset);
        }
        
        let urlPath = `/conversations`;

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

    /**
     * Send an outbound message as the authenticated agent.
     * Send Message
     */
    async sendMessage(sendMessageRequest: SendMessageRequest, initOverrides?: RequestInit): Promise<SendMessageResponse> { 
        if (sendMessageRequest == null) {
            throw new Error(
                'Required parameter "sendMessageRequest" was null or undefined when calling sendMessage().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/conversations/send`;

        return await apiClient.request(
          "POST",
          urlPath,
          SendMessageRequestToJSON(sendMessageRequest),
          initOverrides);

    }

    /**
     * Send a product card into a conversation.
     * Send Product To Conversation
     */
    async sendProductToConversation(conversationId: string, productId: string, initOverrides?: RequestInit): Promise<any> { 
        if (conversationId == null) {
            throw new Error(
                'Required parameter "conversationId" was null or undefined when calling sendProductToConversation().'
            );
        }

        if (productId == null) {
            throw new Error(
                'Required parameter "productId" was null or undefined when calling sendProductToConversation().'
            );
        }

        const queryParameters: Record<string, string> = {};

        if (productId != null) {
            queryParameters['product_id'] = String(productId);
        }
        
        let urlPath = `/conversations/{conversation_id}/send-product`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Update contact opt-out status.
     * Update Contact Opt Out
     */
    async updateContactOptOut(contactId: string, contactOptOutUpdate: ContactOptOutUpdate, initOverrides?: RequestInit): Promise<void> { 
        if (contactId == null) {
            throw new Error(
                'Required parameter "contactId" was null or undefined when calling updateContactOptOut().'
            );
        }

        if (contactOptOutUpdate == null) {
            throw new Error(
                'Required parameter "contactOptOutUpdate" was null or undefined when calling updateContactOptOut().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/conversations/contacts/{contact_id}/optout`;
        urlPath = urlPath.replace(`{${"contact_id"}}`, encodeURIComponent(String(contactId)));

        return await apiClient.request(
          "PATCH",
          urlPath,
          ContactOptOutUpdateToJSON(contactOptOutUpdate),
          initOverrides);

    }

}

export const conversationsApi = new ConversationsApi();