/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  EmailSendRequest,
  EmailSendResponse,
  HTTPValidationError,
} from '../models/index';

/**
 * 
 */
export class EmailApi {

    /**
     * Send Email
     */
    async sendEmail(emailSendRequest: EmailSendRequest, initOverrides?: RequestInit): Promise<EmailSendResponse> { 
        if (emailSendRequest == null) {
            throw new Error(
                'Required parameter "emailSendRequest" was null or undefined when calling sendEmail().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/email/send`;

        return await apiClient.request(
          "POST",
          urlPath,
          emailSendRequest,
          initOverrides);

    }

}

export const emailApi = new EmailApi();