/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  HTTPValidationError,
  ProductCreate,
  ProductListResponse,
  ProductOut,
  ProductUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProductCreateFromJSON,
    ProductCreateToJSON,
    ProductListResponseFromJSON,
    ProductListResponseToJSON,
    ProductOutFromJSON,
    ProductOutToJSON,
    ProductUpdateFromJSON,
    ProductUpdateToJSON,
} from '../models/index';

/**
 * 
 */
export class ProductsApi {

    /**
     * Create a new product (ADMIN only).
     * Create Product
     */
    async createProduct(productCreate: ProductCreate, initOverrides?: RequestInit): Promise<ProductOut> { 
        if (productCreate == null) {
            throw new Error(
                'Required parameter "productCreate" was null or undefined when calling createProduct().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/products`;

        return await apiClient.request(
          "POST",
          urlPath,
          ProductCreateToJSON(productCreate),
          initOverrides);

    }

    /**
     * Soft delete a product (ADMIN only).
     * Delete Product
     */
    async deleteProduct(productId: string, initOverrides?: RequestInit): Promise<void> { 
        if (productId == null) {
            throw new Error(
                'Required parameter "productId" was null or undefined when calling deleteProduct().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/products/{product_id}`;
        urlPath = urlPath.replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));

        return await apiClient.request(
          "DELETE",
          urlPath,
          initOverrides);

    }

    /**
     * Get a specific product.
     * Get Product
     */
    async getProduct(productId: string, initOverrides?: RequestInit): Promise<ProductOut> { 
        if (productId == null) {
            throw new Error(
                'Required parameter "productId" was null or undefined when calling getProduct().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/products/{product_id}`;
        urlPath = urlPath.replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

    /**
     * List products.
     * List Products
     */
    async listProducts(activeOnly?: boolean, search?: string | null, initOverrides?: RequestInit): Promise<ProductListResponse> { 
        const queryParameters: Record<string, string> = {};

        if (activeOnly != null) {
            queryParameters['active_only'] = String(activeOnly);
        }
        if (search != null) {
            queryParameters['search'] = String(search);
        }
        
        let urlPath = `/products`;

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

    /**
     * Update a product (ADMIN only).
     * Update Product
     */
    async updateProduct(productId: string, productUpdate: ProductUpdate, initOverrides?: RequestInit): Promise<ProductOut> { 
        if (productId == null) {
            throw new Error(
                'Required parameter "productId" was null or undefined when calling updateProduct().'
            );
        }

        if (productUpdate == null) {
            throw new Error(
                'Required parameter "productUpdate" was null or undefined when calling updateProduct().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/products/{product_id}`;
        urlPath = urlPath.replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));

        return await apiClient.request(
          "PUT",
          urlPath,
          ProductUpdateToJSON(productUpdate),
          initOverrides);

    }

}

export const productsApi = new ProductsApi();