/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";


/**
 * 
 */
export class ReadyApi {

    /**
     * Ready Db
     */
    async readyDb(initOverrides?: RequestInit): Promise<any> { 
        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/ready-db`;

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

}

export const readyApi = new ReadyApi();