/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  HTTPValidationError,
} from '../models/index';

/**
 * 
 */
export class StripeApi {

    /**
     * Create a Stripe Checkout Session and redirect to payment page.  This endpoint is intentionally PUBLIC. Security is enforced via Stripe webhooks, not here.
     * Create Checkout
     */
    async createCheckout(productId: string, convId?: string | null, contactId?: string | null, initOverrides?: RequestInit): Promise<any> { 
        if (productId == null) {
            throw new Error(
                'Required parameter "productId" was null or undefined when calling createCheckout().'
            );
        }

        const queryParameters: Record<string, string> = {};

        if (productId != null) {
            queryParameters['product_id'] = String(productId);
        }
        if (convId != null) {
            queryParameters['conv_id'] = String(convId);
        }
        if (contactId != null) {
            queryParameters['contact_id'] = String(contactId);
        }
        
        let urlPath = `/br-general/stripe/checkout`;

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

}

export const stripeApi = new StripeApi();