/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  HTTPValidationError,
  UserOut,
  UserProfileUpdate,
} from '../models/index';

/**
 * 
 */
export class UsersApi {

    /**
     * Get current user profile.
     * Get Current User Profile
     */
    async getCurrentUserProfile(initOverrides?: RequestInit): Promise<UserOut> { 
        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/users/me`;

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

    /**
     * Update current user profile.
     * Update Current User Profile
     */
    async updateCurrentUserProfile(userProfileUpdate: UserProfileUpdate, initOverrides?: RequestInit): Promise<UserOut> { 
        if (userProfileUpdate == null) {
            throw new Error(
                'Required parameter "userProfileUpdate" was null or undefined when calling updateCurrentUserProfile().'
            );
        }

        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/users/me`;

        return await apiClient.request(
          "PATCH",
          urlPath,
          userProfileUpdate,
          initOverrides);

    }

}

export const usersApi = new UsersApi();