/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { apiClient } from "src/services/apiClient";

import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

/**
 * 
 */
export class WebhooksApi {

    /**
     * Handle Meta Webhook
     */
    async handleMetaWebhook(initOverrides?: RequestInit): Promise<{ [key: string]: any; }> { 
        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/webhooks/meta`;

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Handle Stripe webhook events.  Processes checkout.session.completed events to create orders and send confirmation messages.
     * Handle Stripe Webhook
     */
    async handleStripeWebhook(initOverrides?: RequestInit): Promise<{ [key: string]: any; }> { 
        const queryParameters: Record<string, string> = {};

        
        let urlPath = `/br-general/webhooks/stripe`;

        return await apiClient.request(
          "POST",
          urlPath,
          initOverrides);

    }

    /**
     * Handle Meta webhook verification challenge.  Meta sends a GET request with hub.mode, hub.verify_token, and hub.challenge. We must return the challenge if the token matches.
     * Verify Meta Webhook
     */
    async verifyMetaWebhook(hubMode: string, hubVerifyToken: string, hubChallenge: string, initOverrides?: RequestInit): Promise<any> { 
        if (hubMode == null) {
            throw new Error(
                'Required parameter "hubMode" was null or undefined when calling verifyMetaWebhook().'
            );
        }

        if (hubVerifyToken == null) {
            throw new Error(
                'Required parameter "hubVerifyToken" was null or undefined when calling verifyMetaWebhook().'
            );
        }

        if (hubChallenge == null) {
            throw new Error(
                'Required parameter "hubChallenge" was null or undefined when calling verifyMetaWebhook().'
            );
        }

        const queryParameters: Record<string, string> = {};

        if (hubMode != null) {
            queryParameters['hub.mode'] = String(hubMode);
        }
        if (hubVerifyToken != null) {
            queryParameters['hub.verify_token'] = String(hubVerifyToken);
        }
        if (hubChallenge != null) {
            queryParameters['hub.challenge'] = String(hubChallenge);
        }
        
        let urlPath = `/br-general/webhooks/meta`;

        return await apiClient.request(
          "GET",
          urlPath,
          initOverrides);

    }

}

export const webhooksApi = new WebhooksApi();