/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';

export interface GenerateDraftRequest {
    conversationId: string;
    style?: string | null;
}

/**
 * AiApi - interface
 * 
 * @export
 * @interface AiApiInterface
 */
export interface AiApiInterface {
    /**
     * Generate an AI-drafted response for a conversation.
     * @summary Generate Draft
     * @param {string} conversationId 
     * @param {string} [style] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    generateDraftRaw(requestParameters: GenerateDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Generate an AI-drafted response for a conversation.
     * Generate Draft
     */
    generateDraft(conversationId: string, style?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Get available canned prompt options.
     * @summary Get Canned Prompts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApiInterface
     */
    getCannedPromptsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get available canned prompt options.
     * Get Canned Prompts
     */
    getCannedPrompts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class AiApi extends runtime.BaseAPI implements AiApiInterface {

    /**
     * Generate an AI-drafted response for a conversation.
     * Generate Draft
     */
    async generateDraftRaw(requestParameters: GenerateDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling generateDraft().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['conversationId'] != null) {
            queryParameters['conversation_id'] = requestParameters['conversationId'];
        }

        if (requestParameters['style'] != null) {
            queryParameters['style'] = requestParameters['style'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/ai/draft`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate an AI-drafted response for a conversation.
     * Generate Draft
     */
    async generateDraft(conversationId: string, style?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateDraftRaw({ conversationId: conversationId, style: style }, initOverrides);
        return await response.value();
    }

    /**
     * Get available canned prompt options.
     * Get Canned Prompts
     */
    async getCannedPromptsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/ai/prompts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get available canned prompt options.
     * Get Canned Prompts
     */
    async getCannedPrompts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getCannedPromptsRaw(initOverrides);
        return await response.value();
    }

}
