/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContactOptOutUpdate,
  ConversationListResponse,
  ConversationStatus,
  ConversationWithContact,
  HTTPValidationError,
  MessageOut,
  SendMessageRequest,
  SendMessageResponse,
  SuggestionOut,
} from '../models/index';

export interface CloseConversationRequest {
    conversationId: string;
}

export interface CreateSuggestionsRequest {
    conversationId: string;
}

export interface GetConversationRequest {
    conversationId: string;
}

export interface GetMessagesRequest {
    conversationId: string;
    limit?: number;
    cursor?: string | null;
}

export interface GetSuggestionsRequest {
    conversationId: string;
}

export interface ListConversationsRequest {
    status?: ConversationStatus | null;
    limit?: number;
    offset?: number;
}

export interface SendMessageOperationRequest {
    sendMessageRequest: SendMessageRequest;
}

export interface SendProductToConversationRequest {
    conversationId: string;
    productId: string;
}

export interface UpdateContactOptOutRequest {
    contactId: string;
    contactOptOutUpdate: ContactOptOutUpdate;
}

/**
 * ConversationsApi - interface
 * 
 * @export
 * @interface ConversationsApiInterface
 */
export interface ConversationsApiInterface {
    /**
     * Close a conversation.
     * @summary Close Conversation
     * @param {string} conversationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    closeConversationRaw(requestParameters: CloseConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Close a conversation.
     * Close Conversation
     */
    closeConversation(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Create Suggestions
     * @param {string} conversationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    createSuggestionsRaw(requestParameters: CreateSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SuggestionOut>>>;

    /**
     * Create Suggestions
     */
    createSuggestions(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SuggestionOut>>;

    /**
     * Get a single conversation.
     * @summary Get Conversation
     * @param {string} conversationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    getConversationRaw(requestParameters: GetConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationWithContact>>;

    /**
     * Get a single conversation.
     * Get Conversation
     */
    getConversation(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationWithContact>;

    /**
     * Get messages for a conversation.
     * @summary Get Messages
     * @param {string} conversationId 
     * @param {number} [limit] 
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    getMessagesRaw(requestParameters: GetMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MessageOut>>>;

    /**
     * Get messages for a conversation.
     * Get Messages
     */
    getMessages(conversationId: string, limit?: number, cursor?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MessageOut>>;

    /**
     * Get suggestions for a conversation. AGENT / ADMIN only.
     * @summary Get Suggestions
     * @param {string} conversationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    getSuggestionsRaw(requestParameters: GetSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SuggestionOut>>>;

    /**
     * Get suggestions for a conversation. AGENT / ADMIN only.
     * Get Suggestions
     */
    getSuggestions(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SuggestionOut>>;

    /**
     * List conversations visible to the current user.
     * @summary List Conversations
     * @param {ConversationStatus} [status] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    listConversationsRaw(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationListResponse>>;

    /**
     * List conversations visible to the current user.
     * List Conversations
     */
    listConversations(status?: ConversationStatus | null, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationListResponse>;

    /**
     * Send an outbound message as the authenticated agent.
     * @summary Send Message
     * @param {SendMessageRequest} sendMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    sendMessageRaw(requestParameters: SendMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendMessageResponse>>;

    /**
     * Send an outbound message as the authenticated agent.
     * Send Message
     */
    sendMessage(sendMessageRequest: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendMessageResponse>;

    /**
     * Send a product card into a conversation.
     * @summary Send Product To Conversation
     * @param {string} conversationId 
     * @param {string} productId Product ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    sendProductToConversationRaw(requestParameters: SendProductToConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Send a product card into a conversation.
     * Send Product To Conversation
     */
    sendProductToConversation(conversationId: string, productId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Update contact opt-out status.
     * @summary Update Contact Opt Out
     * @param {string} contactId 
     * @param {ContactOptOutUpdate} contactOptOutUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    updateContactOptOutRaw(requestParameters: UpdateContactOptOutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update contact opt-out status.
     * Update Contact Opt Out
     */
    updateContactOptOut(contactId: string, contactOptOutUpdate: ContactOptOutUpdate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI implements ConversationsApiInterface {

    /**
     * Close a conversation.
     * Close Conversation
     */
    async closeConversationRaw(requestParameters: CloseConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling closeConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/{conversation_id}/close`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Close a conversation.
     * Close Conversation
     */
    async closeConversation(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.closeConversationRaw({ conversationId: conversationId }, initOverrides);
    }

    /**
     * Create Suggestions
     */
    async createSuggestionsRaw(requestParameters: CreateSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SuggestionOut>>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling createSuggestions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/{conversation_id}/suggestions`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create Suggestions
     */
    async createSuggestions(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SuggestionOut>> {
        const response = await this.createSuggestionsRaw({ conversationId: conversationId }, initOverrides);
        return await response.value();
    }

    /**
     * Get a single conversation.
     * Get Conversation
     */
    async getConversationRaw(requestParameters: GetConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationWithContact>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/{conversation_id}`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a single conversation.
     * Get Conversation
     */
    async getConversation(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationWithContact> {
        const response = await this.getConversationRaw({ conversationId: conversationId }, initOverrides);
        return await response.value();
    }

    /**
     * Get messages for a conversation.
     * Get Messages
     */
    async getMessagesRaw(requestParameters: GetMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MessageOut>>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/{conversation_id}/messages`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get messages for a conversation.
     * Get Messages
     */
    async getMessages(conversationId: string, limit?: number, cursor?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MessageOut>> {
        const response = await this.getMessagesRaw({ conversationId: conversationId, limit: limit, cursor: cursor }, initOverrides);
        return await response.value();
    }

    /**
     * Get suggestions for a conversation. AGENT / ADMIN only.
     * Get Suggestions
     */
    async getSuggestionsRaw(requestParameters: GetSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SuggestionOut>>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getSuggestions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/{conversation_id}/suggestions`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get suggestions for a conversation. AGENT / ADMIN only.
     * Get Suggestions
     */
    async getSuggestions(conversationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SuggestionOut>> {
        const response = await this.getSuggestionsRaw({ conversationId: conversationId }, initOverrides);
        return await response.value();
    }

    /**
     * List conversations visible to the current user.
     * List Conversations
     */
    async listConversationsRaw(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List conversations visible to the current user.
     * List Conversations
     */
    async listConversations(status?: ConversationStatus | null, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationListResponse> {
        const response = await this.listConversationsRaw({ status: status, limit: limit, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Send an outbound message as the authenticated agent.
     * Send Message
     */
    async sendMessageRaw(requestParameters: SendMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendMessageResponse>> {
        if (requestParameters['sendMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'sendMessageRequest',
                'Required parameter "sendMessageRequest" was null or undefined when calling sendMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/send`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sendMessageRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Send an outbound message as the authenticated agent.
     * Send Message
     */
    async sendMessage(sendMessageRequest: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendMessageResponse> {
        const response = await this.sendMessageRaw({ sendMessageRequest: sendMessageRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Send a product card into a conversation.
     * Send Product To Conversation
     */
    async sendProductToConversationRaw(requestParameters: SendProductToConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling sendProductToConversation().'
            );
        }

        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling sendProductToConversation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/{conversation_id}/send-product`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Send a product card into a conversation.
     * Send Product To Conversation
     */
    async sendProductToConversation(conversationId: string, productId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.sendProductToConversationRaw({ conversationId: conversationId, productId: productId }, initOverrides);
        return await response.value();
    }

    /**
     * Update contact opt-out status.
     * Update Contact Opt Out
     */
    async updateContactOptOutRaw(requestParameters: UpdateContactOptOutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling updateContactOptOut().'
            );
        }

        if (requestParameters['contactOptOutUpdate'] == null) {
            throw new runtime.RequiredError(
                'contactOptOutUpdate',
                'Required parameter "contactOptOutUpdate" was null or undefined when calling updateContactOptOut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/conversations/contacts/{contact_id}/optout`;
        urlPath = urlPath.replace(`{${"contact_id"}}`, encodeURIComponent(String(requestParameters['contactId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['contactOptOutUpdate'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update contact opt-out status.
     * Update Contact Opt Out
     */
    async updateContactOptOut(contactId: string, contactOptOutUpdate: ContactOptOutUpdate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateContactOptOutRaw({ contactId: contactId, contactOptOutUpdate: contactOptOutUpdate }, initOverrides);
    }

}
