/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmailSendRequest,
  EmailSendResponse,
  HTTPValidationError,
} from '../models/index';

export interface SendEmailRequest {
    emailSendRequest: EmailSendRequest;
}

/**
 * EmailApi - interface
 * 
 * @export
 * @interface EmailApiInterface
 */
export interface EmailApiInterface {
    /**
     * 
     * @summary Send Email
     * @param {EmailSendRequest} emailSendRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    sendEmailRaw(requestParameters: SendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailSendResponse>>;

    /**
     * Send Email
     */
    sendEmail(emailSendRequest: EmailSendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailSendResponse>;

}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI implements EmailApiInterface {

    /**
     * Send Email
     */
    async sendEmailRaw(requestParameters: SendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailSendResponse>> {
        if (requestParameters['emailSendRequest'] == null) {
            throw new runtime.RequiredError(
                'emailSendRequest',
                'Required parameter "emailSendRequest" was null or undefined when calling sendEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/email/send`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['emailSendRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Send Email
     */
    async sendEmail(emailSendRequest: EmailSendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailSendResponse> {
        const response = await this.sendEmailRaw({ emailSendRequest: emailSendRequest }, initOverrides);
        return await response.value();
    }

}
