/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ProductCreate,
  ProductListResponse,
  ProductOut,
  ProductUpdate,
} from '../models/index';

export interface CreateProductRequest {
    productCreate: ProductCreate;
}

export interface DeleteProductRequest {
    productId: string;
}

export interface GetProductRequest {
    productId: string;
}

export interface ListProductsRequest {
    activeOnly?: boolean;
    search?: string | null;
}

export interface UpdateProductRequest {
    productId: string;
    productUpdate: ProductUpdate;
}

/**
 * ProductsApi - interface
 * 
 * @export
 * @interface ProductsApiInterface
 */
export interface ProductsApiInterface {
    /**
     * Create a new product (ADMIN only).
     * @summary Create Product
     * @param {ProductCreate} productCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductRaw(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOut>>;

    /**
     * Create a new product (ADMIN only).
     * Create Product
     */
    createProduct(productCreate: ProductCreate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOut>;

    /**
     * Soft delete a product (ADMIN only).
     * @summary Delete Product
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    deleteProductRaw(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Soft delete a product (ADMIN only).
     * Delete Product
     */
    deleteProduct(productId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Get a specific product.
     * @summary Get Product
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOut>>;

    /**
     * Get a specific product.
     * Get Product
     */
    getProduct(productId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOut>;

    /**
     * List products.
     * @summary List Products
     * @param {boolean} [activeOnly] 
     * @param {string} [search] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductListResponse>>;

    /**
     * List products.
     * List Products
     */
    listProducts(activeOnly?: boolean, search?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductListResponse>;

    /**
     * Update a product (ADMIN only).
     * @summary Update Product
     * @param {string} productId 
     * @param {ProductUpdate} productUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    updateProductRaw(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOut>>;

    /**
     * Update a product (ADMIN only).
     * Update Product
     */
    updateProduct(productId: string, productUpdate: ProductUpdate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOut>;

}

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI implements ProductsApiInterface {

    /**
     * Create a new product (ADMIN only).
     * Create Product
     */
    async createProductRaw(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOut>> {
        if (requestParameters['productCreate'] == null) {
            throw new runtime.RequiredError(
                'productCreate',
                'Required parameter "productCreate" was null or undefined when calling createProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/products`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['productCreate'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create a new product (ADMIN only).
     * Create Product
     */
    async createProduct(productCreate: ProductCreate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOut> {
        const response = await this.createProductRaw({ productCreate: productCreate }, initOverrides);
        return await response.value();
    }

    /**
     * Soft delete a product (ADMIN only).
     * Delete Product
     */
    async deleteProductRaw(requestParameters: DeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling deleteProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/products/{product_id}`;
        urlPath = urlPath.replace(`{${"product_id"}}`, encodeURIComponent(String(requestParameters['productId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft delete a product (ADMIN only).
     * Delete Product
     */
    async deleteProduct(productId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProductRaw({ productId: productId }, initOverrides);
    }

    /**
     * Get a specific product.
     * Get Product
     */
    async getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOut>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling getProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/products/{product_id}`;
        urlPath = urlPath.replace(`{${"product_id"}}`, encodeURIComponent(String(requestParameters['productId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a specific product.
     * Get Product
     */
    async getProduct(productId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOut> {
        const response = await this.getProductRaw({ productId: productId }, initOverrides);
        return await response.value();
    }

    /**
     * List products.
     * List Products
     */
    async listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['activeOnly'] != null) {
            queryParameters['active_only'] = requestParameters['activeOnly'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/products`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List products.
     * List Products
     */
    async listProducts(activeOnly?: boolean, search?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductListResponse> {
        const response = await this.listProductsRaw({ activeOnly: activeOnly, search: search }, initOverrides);
        return await response.value();
    }

    /**
     * Update a product (ADMIN only).
     * Update Product
     */
    async updateProductRaw(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOut>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['productUpdate'] == null) {
            throw new runtime.RequiredError(
                'productUpdate',
                'Required parameter "productUpdate" was null or undefined when calling updateProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/products/{product_id}`;
        urlPath = urlPath.replace(`{${"product_id"}}`, encodeURIComponent(String(requestParameters['productId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['productUpdate'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update a product (ADMIN only).
     * Update Product
     */
    async updateProduct(productId: string, productUpdate: ProductUpdate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOut> {
        const response = await this.updateProductRaw({ productId: productId, productUpdate: productUpdate }, initOverrides);
        return await response.value();
    }

}
