/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * ReadyApi - interface
 * 
 * @export
 * @interface ReadyApiInterface
 */
export interface ReadyApiInterface {
    /**
     * 
     * @summary Ready Db
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReadyApiInterface
     */
    readyDbRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Ready Db
     */
    readyDb(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class ReadyApi extends runtime.BaseAPI implements ReadyApiInterface {

    /**
     * Ready Db
     */
    async readyDbRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/br-general/ready-db`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Ready Db
     */
    async readyDb(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.readyDbRaw(initOverrides);
        return await response.value();
    }

}
