/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';

export interface CreateCheckoutRequest {
    productId: string;
    convId?: string | null;
    contactId?: string | null;
}

/**
 * StripeApi - interface
 * 
 * @export
 * @interface StripeApiInterface
 */
export interface StripeApiInterface {
    /**
     * Create a Stripe Checkout Session and redirect to payment page.  This endpoint is intentionally PUBLIC. Security is enforced via Stripe webhooks, not here.
     * @summary Create Checkout
     * @param {string} productId 
     * @param {string} [convId] 
     * @param {string} [contactId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StripeApiInterface
     */
    createCheckoutRaw(requestParameters: CreateCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Create a Stripe Checkout Session and redirect to payment page.  This endpoint is intentionally PUBLIC. Security is enforced via Stripe webhooks, not here.
     * Create Checkout
     */
    createCheckout(productId: string, convId?: string | null, contactId?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class StripeApi extends runtime.BaseAPI implements StripeApiInterface {

    /**
     * Create a Stripe Checkout Session and redirect to payment page.  This endpoint is intentionally PUBLIC. Security is enforced via Stripe webhooks, not here.
     * Create Checkout
     */
    async createCheckoutRaw(requestParameters: CreateCheckoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling createCheckout().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['convId'] != null) {
            queryParameters['conv_id'] = requestParameters['convId'];
        }

        if (requestParameters['contactId'] != null) {
            queryParameters['contact_id'] = requestParameters['contactId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/br-general/stripe/checkout`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create a Stripe Checkout Session and redirect to payment page.  This endpoint is intentionally PUBLIC. Security is enforced via Stripe webhooks, not here.
     * Create Checkout
     */
    async createCheckout(productId: string, convId?: string | null, contactId?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createCheckoutRaw({ productId: productId, convId: convId, contactId: contactId }, initOverrides);
        return await response.value();
    }

}
