/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  UserOut,
  UserProfileUpdate,
} from '../models/index';

export interface UpdateCurrentUserProfileRequest {
    userProfileUpdate: UserProfileUpdate;
}

/**
 * UsersApi - interface
 * 
 * @export
 * @interface UsersApiInterface
 */
export interface UsersApiInterface {
    /**
     * Get current user profile.
     * @summary Get Current User Profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getCurrentUserProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOut>>;

    /**
     * Get current user profile.
     * Get Current User Profile
     */
    getCurrentUserProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOut>;

    /**
     * Update current user profile.
     * @summary Update Current User Profile
     * @param {UserProfileUpdate} userProfileUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    updateCurrentUserProfileRaw(requestParameters: UpdateCurrentUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOut>>;

    /**
     * Update current user profile.
     * Update Current User Profile
     */
    updateCurrentUserProfile(userProfileUpdate: UserProfileUpdate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOut>;

}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI implements UsersApiInterface {

    /**
     * Get current user profile.
     * Get Current User Profile
     */
    async getCurrentUserProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOut>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get current user profile.
     * Get Current User Profile
     */
    async getCurrentUserProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOut> {
        const response = await this.getCurrentUserProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update current user profile.
     * Update Current User Profile
     */
    async updateCurrentUserProfileRaw(requestParameters: UpdateCurrentUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserOut>> {
        if (requestParameters['userProfileUpdate'] == null) {
            throw new runtime.RequiredError(
                'userProfileUpdate',
                'Required parameter "userProfileUpdate" was null or undefined when calling updateCurrentUserProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/br-general/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['userProfileUpdate'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update current user profile.
     * Update Current User Profile
     */
    async updateCurrentUserProfile(userProfileUpdate: UserProfileUpdate, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserOut> {
        const response = await this.updateCurrentUserProfileRaw({ userProfileUpdate: userProfileUpdate }, initOverrides);
        return await response.value();
    }

}
