/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';

export interface VerifyMetaWebhookRequest {
    hubMode: string;
    hubVerifyToken: string;
    hubChallenge: string;
}

/**
 * WebhooksApi - interface
 * 
 * @export
 * @interface WebhooksApiInterface
 */
export interface WebhooksApiInterface {
    /**
     * 
     * @summary Handle Meta Webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    handleMetaWebhookRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Handle Meta Webhook
     */
    handleMetaWebhook(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Handle Stripe webhook events.  Processes checkout.session.completed events to create orders and send confirmation messages.
     * @summary Handle Stripe Webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    handleStripeWebhookRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Handle Stripe webhook events.  Processes checkout.session.completed events to create orders and send confirmation messages.
     * Handle Stripe Webhook
     */
    handleStripeWebhook(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Handle Meta webhook verification challenge.  Meta sends a GET request with hub.mode, hub.verify_token, and hub.challenge. We must return the challenge if the token matches.
     * @summary Verify Meta Webhook
     * @param {string} hubMode 
     * @param {string} hubVerifyToken 
     * @param {string} hubChallenge 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    verifyMetaWebhookRaw(requestParameters: VerifyMetaWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Handle Meta webhook verification challenge.  Meta sends a GET request with hub.mode, hub.verify_token, and hub.challenge. We must return the challenge if the token matches.
     * Verify Meta Webhook
     */
    verifyMetaWebhook(hubMode: string, hubVerifyToken: string, hubChallenge: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI implements WebhooksApiInterface {

    /**
     * Handle Meta Webhook
     */
    async handleMetaWebhookRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/br-general/webhooks/meta`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Handle Meta Webhook
     */
    async handleMetaWebhook(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.handleMetaWebhookRaw(initOverrides);
        return await response.value();
    }

    /**
     * Handle Stripe webhook events.  Processes checkout.session.completed events to create orders and send confirmation messages.
     * Handle Stripe Webhook
     */
    async handleStripeWebhookRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/br-general/webhooks/stripe`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Handle Stripe webhook events.  Processes checkout.session.completed events to create orders and send confirmation messages.
     * Handle Stripe Webhook
     */
    async handleStripeWebhook(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.handleStripeWebhookRaw(initOverrides);
        return await response.value();
    }

    /**
     * Handle Meta webhook verification challenge.  Meta sends a GET request with hub.mode, hub.verify_token, and hub.challenge. We must return the challenge if the token matches.
     * Verify Meta Webhook
     */
    async verifyMetaWebhookRaw(requestParameters: VerifyMetaWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['hubMode'] == null) {
            throw new runtime.RequiredError(
                'hubMode',
                'Required parameter "hubMode" was null or undefined when calling verifyMetaWebhook().'
            );
        }

        if (requestParameters['hubVerifyToken'] == null) {
            throw new runtime.RequiredError(
                'hubVerifyToken',
                'Required parameter "hubVerifyToken" was null or undefined when calling verifyMetaWebhook().'
            );
        }

        if (requestParameters['hubChallenge'] == null) {
            throw new runtime.RequiredError(
                'hubChallenge',
                'Required parameter "hubChallenge" was null or undefined when calling verifyMetaWebhook().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['hubMode'] != null) {
            queryParameters['hub.mode'] = requestParameters['hubMode'];
        }

        if (requestParameters['hubVerifyToken'] != null) {
            queryParameters['hub.verify_token'] = requestParameters['hubVerifyToken'];
        }

        if (requestParameters['hubChallenge'] != null) {
            queryParameters['hub.challenge'] = requestParameters['hubChallenge'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/br-general/webhooks/meta`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handle Meta webhook verification challenge.  Meta sends a GET request with hub.mode, hub.verify_token, and hub.challenge. We must return the challenge if the token matches.
     * Verify Meta Webhook
     */
    async verifyMetaWebhook(hubMode: string, hubVerifyToken: string, hubChallenge: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.verifyMetaWebhookRaw({ hubMode: hubMode, hubVerifyToken: hubVerifyToken, hubChallenge: hubChallenge }, initOverrides);
        return await response.value();
    }

}
