import {atom} from "jotai";
import {UserOut} from "src/apiAutogenerated/typescript-fetch/models";
import {
  getUserProfile,
  patchUserProfile,
} from "src/services/profileService";

const userProfileAtom = atom<UserOut | null>(null);
const userProfileLoadingAtom = atom<boolean>(false);
const userProfileErrorAtom = atom<string | null>(null);

export const userProfileStateAtom = atom((get) => ({
  userProfile: get(userProfileAtom),
  userProfileLoading: get(userProfileLoadingAtom),
  userProfileError: get(userProfileErrorAtom),
}));

export const loadUserProfileAtom = atom(
  null,
  async (_get, set): Promise<void> => {
    set(userProfileLoadingAtom, true);
    set(userProfileErrorAtom, null);

    try {
      const profile = await getUserProfile();

      set(userProfileAtom, profile);
    } catch (error) {
      if (error instanceof Error) {
        set(userProfileErrorAtom, error.message);
      } else {
        set(userProfileErrorAtom, "Неизвестная ошибка загрузки данных");
      }
    } finally {
      set(userProfileLoadingAtom, false);
    }
  },
);

export const updateUserProfileAtom = atom(
  null,
  async (
    get,
    set,
    update: Partial<Pick<UserOut, "name" | "email">>,
  ): Promise<void> => {
    await patchUserProfile(update);

    const previousProfile = get(userProfileAtom);
    if (previousProfile) {
      set(userProfileAtom, {...previousProfile, ...update});
    }
  },
);

export const clearUserProfileAtom = atom(null, (_get, set) => {
  set(userProfileAtom, null);
  set(userProfileLoadingAtom, false);
  set(userProfileErrorAtom, null);
});
