import {atom} from "jotai";
import {UserOut} from "src/apiAutogenerated/typescript-fetch/models";
import {
  getUserProfile,
  patchUserProfile,
} from "src/services/profileService";

export const userProfileAtom = atom<UserOut | null>(null);
export const userLoadingAtom = atom<boolean>(false);
export const userErrorAtom = atom<string | null>(null);

export const loadUserDataAtom = atom(
  null,
  async (_get, set): Promise<void> => {
    set(userLoadingAtom, true);
    set(userErrorAtom, null);

    try {
      const profile = await getUserProfile();

      set(userProfileAtom, profile);
    } catch (error) {
      if (error instanceof Error) {
        set(userErrorAtom, error.message);
      } else {
        set(userErrorAtom, "Неизвестная ошибка загрузки данных");
      }
    } finally {
      set(userLoadingAtom, false);
    }
  },
);

export const updateUserProfileAtom = atom(
  null,
  async (
    get,
    set,
    update: Partial<Pick<UserOut, "name" | "email">>,
  ): Promise<void> => {
    await patchUserProfile(update);

    const previousProfile = get(userProfileAtom);
    if (previousProfile) {
      set(userProfileAtom, {...previousProfile, ...update});
    }
  },
);

export const clearUserProfileAtom = atom(null, (_get, set) => {
  set(userProfileAtom, null);
  set(userLoadingAtom, false);
  set(userErrorAtom, null);
});
