import {conversationsApi} from "src/apiAutogenerated/typescript-fetch/apis";
import {
  MessageOut,
  SendMessageRequest,
  SendMessageResponse,
  SuggestionOut,
} from "src/apiAutogenerated/typescript-fetch/models";
import {ConversationStatusOld} from "src/constants/conversationStatus";
import {
  ConversationListModel,
  conversationListModelFromConversationListResponse,
  ConversationModel,
  conversationModelFromConversationWithContact,
} from "src/models/Conversation";

export async function getConversationList(
  status?: ConversationStatusOld,
  offset?: number,
  limit?: number): Promise<ConversationListModel> {

  return conversationListModelFromConversationListResponse(await conversationsApi.listConversations(status, limit, offset));
}

export async function getConversation(conversationId: string): Promise<ConversationModel> {
  return conversationModelFromConversationWithContact(await conversationsApi.getConversation(conversationId));
}

export async function getMessages(conversationId: string, limit?: number, cursor?: string): Promise<MessageOut[]> {
  return conversationsApi.getMessages(conversationId, limit, cursor);
}

export async function sendMessage(payload: SendMessageRequest): Promise<SendMessageResponse> {
  return conversationsApi.sendMessage(payload);
}

export async function getSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return conversationsApi.getSuggestions(conversationId);
}

export async function createSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return conversationsApi.createSuggestions(conversationId);
}
