import {conversationsApi} from "src/apiAutogenerated/typescript-fetch/apis";
import {
  SendMessageRequest,
  SuggestionOut,
} from "src/apiAutogenerated/typescript-fetch/models";
import {
  ConversationListModel,
  conversationListModelFromConversationListResponse,
  ConversationModel,
  conversationModelFromConversationWithContact,
  ConversationStatus,
} from "src/models/Conversation";
import {MessageModel, messageModelListFromMessageOutList} from "src/models/Message";

export async function getConversationList(
  status?: ConversationStatus,
  offset?: number,
  limit?: number): Promise<ConversationListModel> {

  return conversationListModelFromConversationListResponse(await conversationsApi.listConversations(status, limit, offset));
}

export async function getConversation(conversationId: string): Promise<ConversationModel> {
  return conversationModelFromConversationWithContact(await conversationsApi.getConversation(conversationId));
}

export async function getMessages(conversationId: string, limit?: number, cursor?: string): Promise<MessageModel[]> {
  return messageModelListFromMessageOutList(await conversationsApi.getMessages(conversationId, limit, cursor));
}

export async function sendMessage(payload: SendMessageRequest): Promise<void> {
  await conversationsApi.sendMessage(payload);
}

export async function getSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return await conversationsApi.getSuggestions(conversationId);
}

export async function createSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return await conversationsApi.createSuggestions(conversationId);
}
