import {conversationsApi} from "src/apiAutogenerated/typescript-fetch/apis";
import {
  ConversationListResponse,
  ConversationWithContact,
  MessageOut,
  SendMessageRequest,
  SendMessageResponse,
  SuggestionOut,
} from "src/apiAutogenerated/typescript-fetch/models";
import {ConversationStatus} from "src/constants/conversationStatus";

export async function getConversationList(
  status?: ConversationStatus,
  offset?: number,
  limit?: number): Promise<ConversationListResponse> {

  return conversationsApi.listConversations(status, limit, offset);
}

export async function getConversation(conversationId: string): Promise<ConversationWithContact> {
  return conversationsApi.getConversation(conversationId);
}

export async function getMessages(conversationId: string, limit?: number, cursor?: string): Promise<MessageOut[]> {
  return conversationsApi.getMessages(conversationId, limit, cursor);
}

export async function sendMessage(payload: SendMessageRequest): Promise<SendMessageResponse> {
  return conversationsApi.sendMessage(payload);
}

export async function getSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return conversationsApi.getSuggestions(conversationId);
}

export async function createSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return conversationsApi.createSuggestions(conversationId);
}
