import {healthApi} from "src/apiAutogenerated/typescript-fetch/apis";
export class DevApi {

  public static async checkHealth() {
    const data = await healthApi.root();

    // eslint-disable-next-line no-console
    console.log(data);
  }

}

