import {usersApi} from "src/apiAutogenerated/typescript-fetch/apis";
import {UserProfileUpdate} from "src/apiAutogenerated/typescript-fetch/models";
import {UserProfileModel, userProfileModelFromUserOut} from "src/models/UserProfile";

export async function getUserProfile(init?: { signal?: AbortSignal }): Promise<UserProfileModel> {
  return userProfileModelFromUserOut(await usersApi.getCurrentUserProfile(init));
}

export async function patchUserProfile(update: Partial<Pick<UserProfileUpdate, "name" | "email">>): Promise<void> {
  await usersApi.updateCurrentUserProfile(update);
}
