import {usersApi} from "src/apiAutogenerated/typescript-fetch/apis";
import {UserProfileModel, userProfileModelFromUserOut} from "src/models/UserProfile";

export async function getUserProfile(init?: { signal?: AbortSignal }): Promise<UserProfileModel> {
  return userProfileModelFromUserOut(await usersApi.getCurrentUserProfile(init));
}

type UpdateUserProfilePayload = Partial<Pick<UserProfileModel, "name" | "email">>

export async function patchUserProfile(payload: UpdateUserProfilePayload): Promise<void> {
  await usersApi.updateCurrentUserProfile(payload);
}
