import {conversationsApi} from "src/apiAutogenerated/typescript-fetch";
import {SuggestionOut} from "src/apiAutogenerated/typescript-fetch/models";

export async function getSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return conversationsApi.getSuggestions(conversationId);
}

export async function createSuggestions(conversationId: string): Promise<SuggestionOut[]> {
  return conversationsApi.createSuggestions(conversationId);
}
