import {ConversationWithContact} from "src/apiAutogenerated/typescript-fetch/models";
import {toAgoString} from "src/utils/dateFormat";
import styles from "src/components/Chat/ConversationList/ConversationCard/ConversationCard.module.scss";

const DEFAULT_AVATAR_SYMBOL = "?";

interface ConversationCardProps {
  conversation: ConversationWithContact;
  onCardClick: () => void;
}

export function ConversationCard({conversation, onCardClick}: ConversationCardProps) {
  const defaultLastMessage = "Lorem, ipsum dolor sit amet consectetur adipisicing elit";

  return (
    <div
      className={styles.conversationCard}
      onClick={onCardClick}
    >
      <div className={styles.avatarWrapper}>
        <p className={styles.avatar}>
          {conversation.contact.name ? conversation.contact.name[0].toUpperCase() : DEFAULT_AVATAR_SYMBOL}
        </p>
      </div>
      <div className={styles.infoWrapper}>
        <div className={styles.nameWrapper}>
          <p className={styles.name}>
            {conversation.contact.name}
          </p>
          <p className={styles.lastMessageDate}>
            {toAgoString(conversation.lastMessageAt.toString())}
          </p>
        </div>
        <p className={styles.lastMessage}>
          {defaultLastMessage}
        </p>
      </div>
    </div>
  );
}
